<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Proyecto', 'doctrine');

/**
 * BaseProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descrpicion
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method string   getNombre()      Returns the current record's "nombre" value
 * @method string   getDescrpicion() Returns the current record's "descrpicion" value
 * @method Proyecto setId()          Sets the current record's "id" value
 * @method Proyecto setNombre()      Sets the current record's "nombre" value
 * @method Proyecto setDescrpicion() Sets the current record's "descrpicion" value
 * 
 * @package    proyectosm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proyecto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('descrpicion', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}