<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contacto', 'doctrine');

/**
 * BaseContacto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idproyecto
 * @property string $nombre
 * @property string $telefono
 * @property string $pais
 * @property string $departamento
 * @property string $municipio
 * 
 * @method integer  getId()           Returns the current record's "id" value
 * @method integer  getIdproyecto()   Returns the current record's "idproyecto" value
 * @method string   getNombre()       Returns the current record's "nombre" value
 * @method string   getTelefono()     Returns the current record's "telefono" value
 * @method string   getPais()         Returns the current record's "pais" value
 * @method string   getDepartamento() Returns the current record's "departamento" value
 * @method string   getMunicipio()    Returns the current record's "municipio" value
 * @method Contacto setId()           Sets the current record's "id" value
 * @method Contacto setIdproyecto()   Sets the current record's "idproyecto" value
 * @method Contacto setNombre()       Sets the current record's "nombre" value
 * @method Contacto setTelefono()     Sets the current record's "telefono" value
 * @method Contacto setPais()         Sets the current record's "pais" value
 * @method Contacto setDepartamento() Sets the current record's "departamento" value
 * @method Contacto setMunicipio()    Sets the current record's "municipio" value
 * 
 * @package    proyectosm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContacto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idproyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('telefono', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('pais', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('departamento', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('municipio', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}