<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Departamentos', 'doctrine');

/**
 * BaseDepartamentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_departamento
 * @property string $departamento
 * 
 * @method integer       getId_departamento() Returns the current record's "id_departamento" value
 * @method string        getDepartamento()    Returns the current record's "departamento" value
 * @method Departamentos setId_departamento() Sets the current record's "id_departamento" value
 * @method Departamentos setDepartamento()    Sets the current record's "departamento" value
 * 
 * @package    proyectosm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartamentos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('departamentos');
        $this->hasColumn('id_departamento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('departamento', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}