<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rol', 'doctrine');

/**
 * BaseRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Usuario
 * @property Doctrine_Collection $Usuario_3
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getUsuario()   Returns the current record's "Usuario" collection
 * @method Doctrine_Collection getUsuario3()  Returns the current record's "Usuario_3" collection
 * @method Rol                 setId()        Sets the current record's "id" value
 * @method Rol                 setNombre()    Sets the current record's "nombre" value
 * @method Rol                 setUsuario()   Sets the current record's "Usuario" collection
 * @method Rol                 setUsuario3()  Sets the current record's "Usuario_3" collection
 * 
 * @package    proyectosm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rol');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario', array(
             'local' => 'id',
             'foreign' => 'rol'));

        $this->hasMany('Usuario as Usuario_3', array(
             'local' => 'id',
             'foreign' => 'rol'));
    }
}