<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EtapaProyecto', 'doctrine');

/**
 * BaseEtapaProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idetaparef
 * @property integer $idproyecto
 * @property string $informacion
 * @property date $inicio
 * @property date $fin
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getIdetaparef()  Returns the current record's "idetaparef" value
 * @method integer       getIdproyecto()  Returns the current record's "idproyecto" value
 * @method string        getInformacIon() Returns the current record's "informacion" value
 * @method date          getInIcIo()      Returns the current record's "inicio" value
 * @method date          getFin()         Returns the current record's "fin" value
 * @method EtapaProyecto setId()          Sets the current record's "id" value
 * @method EtapaProyecto setIdetaparef()  Sets the current record's "idetaparef" value
 * @method EtapaProyecto setIdproyecto()  Sets the current record's "idproyecto" value
 * @method EtapaProyecto setInformacIon() Sets the current record's "informacion" value
 * @method EtapaProyecto setInIcIo()      Sets the current record's "inicio" value
 * @method EtapaProyecto setFin()         Sets the current record's "fin" value
 * 
 * @package    proyectosm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEtapaProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('etapa_proyecto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idetaparef', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idproyecto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('informacion', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 300,
             ));
        $this->hasColumn('inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fin', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}