<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Actividad', 'doctrine');

/**
 * BaseActividad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idarea
 * @property integer $idusuario
 * @property string $nombre
 * @property string $descripcion
 * @property date $fechacreacion
 * @property date $fechacompletada
 * @property integer $porcentajeavance
 * @property string $estado
 * 
 * @method integer   getId()               Returns the current record's "id" value
 * @method integer   getIdarea()           Returns the current record's "idarea" value
 * @method integer   getIdusuarIo()        Returns the current record's "idusuario" value
 * @method string    getNombre()           Returns the current record's "nombre" value
 * @method string    getDescripcion()      Returns the current record's "descripcion" value
 * @method date      getFechacreacion()    Returns the current record's "fechacreacion" value
 * @method date      getFechacompletada()  Returns the current record's "fechacompletada" value
 * @method integer   getPorcentajeavance() Returns the current record's "porcentajeavance" value
 * @method string    getEstado()           Returns the current record's "estado" value
 * @method Actividad setId()               Sets the current record's "id" value
 * @method Actividad setIdarea()           Sets the current record's "idarea" value
 * @method Actividad setIdusuarIo()        Sets the current record's "idusuario" value
 * @method Actividad setNombre()           Sets the current record's "nombre" value
 * @method Actividad setDescripcion()      Sets the current record's "descripcion" value
 * @method Actividad setFechacreacion()    Sets the current record's "fechacreacion" value
 * @method Actividad setFechacompletada()  Sets the current record's "fechacompletada" value
 * @method Actividad setPorcentajeavance() Sets the current record's "porcentajeavance" value
 * @method Actividad setEstado()           Sets the current record's "estado" value
 * 
 * @package    proyectosm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActividad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actividad');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idarea', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idusuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('fechacreacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fechacompletada', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('porcentajeavance', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}