<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/09/30 00:43:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=proyectosm',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
