<?php

/**
 * AreaproduccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AreaproduccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AreaproduccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Areaproduccion');
    }
}