<?php

/**
 * EtapaProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtapaProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtapaProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EtapaProyecto');
    }
}