<?php

/**
 * EtapaRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtapaRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtapaRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EtapaRef');
    }
}